# Generated by Django 3.0.10 on 2021-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sprites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_shiny', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='back shiny')),
                ('back_female', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='back female')),
                ('front_shiny', models.URLField(blank=True, db_index=True, max_length=300, unique=True, verbose_name='front shiny')),
                ('back_default', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='Back Default')),
                ('front_female', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='Front Female')),
                ('front_default', models.URLField(blank=True, db_index=True, max_length=300, unique=True, verbose_name='Front Female')),
                ('back_shiny_female', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='back shiny female')),
                ('front_shiny_female', models.URLField(db_index=True, max_length=300, null=True, unique=True, verbose_name='front shiny female')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_rate', models.FloatField(null=True, verbose_name='Capture Rate')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('flavor_text', models.TextField(verbose_name='flavor text')),
                ('height', models.FloatField(null=True, verbose_name='Height')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('weight', models.FloatField(null=True, verbose_name='Weight')),
                ('Stats', models.ManyToManyField(related_name='Stats', to='PokemonApp.Sprites')),
                ('abilities', models.ManyToManyField(related_name='Abilities', to='PokemonApp.Abilities')),
                ('sprites', models.ManyToManyField(related_name='Sprites', to='PokemonApp.Sprites')),
            ],
        ),
    ]
