# Generated by Django 3.0.10 on 2021-06-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_rate', models.FloatField(null=True, verbose_name='Capture Rate')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('flavor_text', models.TextField(verbose_name='flavor text')),
                ('height', models.FloatField(null=True, verbose_name='Height')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('weight', models.FloatField(null=True, verbose_name='Weight')),
                ('abilities', models.ManyToManyField(related_name='Abilities', to='PokemonApp.Abilities')),
                ('moves', models.ManyToManyField(related_name='Moves', to='PokemonApp.Moves')),
            ],
        ),
        migrations.CreateModel(
            name='Sprites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_shiny', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back shiny')),
                ('back_female', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back female')),
                ('front_shiny', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front shiny')),
                ('back_default', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Back Default')),
                ('front_female', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Front Female')),
                ('front_default', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front default')),
                ('back_shiny_female', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back shiny female')),
                ('front_shiny_female', models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front shiny female')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('location', models.ManyToManyField(related_name='Location', to='PokemonApp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCaptured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=40, verbose_name='Nick Name')),
                ('is_party_member', models.BooleanField()),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Sprites'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.ManyToManyField(related_name='Stats', to='PokemonApp.Stats'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='Types', to='PokemonApp.Types'),
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Location')),
                ('pokemons', models.ManyToManyField(related_name='Pokemon', to='PokemonApp.Pokemon')),
            ],
        ),
    ]
