# Generated by Django 3.0.10 on 2021-06-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncaptured',
            name='nick_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
