# Generated by Django 3.0.10 on 2021-06-13 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='Stats',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='sprites',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='Types',
            field=models.ManyToManyField(related_name='Stats', to='PokemonApp.Types'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(related_name='Moves', to='PokemonApp.Moves'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.ManyToManyField(related_name='Stats', to='PokemonApp.Stats'),
        ),
        migrations.AddField(
            model_name='sprites',
            name='pokemon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Pokemon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_default',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='Back Default'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='back female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_shiny',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='back shiny'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_shiny_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='back shiny female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_default',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='front default'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='Front Female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_shiny',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='front shiny'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_shiny_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, unique=True, verbose_name='front shiny female'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('areas', models.ManyToManyField(related_name='Location', to='PokemonApp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Location')),
                ('pokemons', models.ManyToManyField(related_name='Pokemon', to='PokemonApp.Pokemon')),
            ],
        ),
    ]
