# Generated by Django 3.0.10 on 2021-06-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0002_auto_20210612_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='Types',
        ),
        migrations.RemoveField(
            model_name='sprites',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.ManyToManyField(related_name='Sprites', to='PokemonApp.Sprites'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='Types', to='PokemonApp.Types'),
        ),
    ]
