# Generated by Django 3.0.10 on 2021-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0003_auto_20210612_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprites',
            name='back_default',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Back Default'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_shiny',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back shiny'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='back_shiny_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='back shiny female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_default',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front default'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Front Female'),
        ),
        migrations.AlterField(
            model_name='sprites',
            name='front_shiny',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front shiny'),
        ),
    ]
