# Generated by Django 3.0.10 on 2021-06-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0004_auto_20210613_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprites',
            name='front_shiny_female',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True, verbose_name='front shiny female'),
        ),
    ]
