# Generated by Django 3.0.10 on 2021-06-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0005_auto_20210613_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='areas',
            new_name='location',
        ),
    ]
