# Generated by Django 3.0.10 on 2021-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0007_auto_20210613_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
