# Generated by Django 3.0.10 on 2021-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0008_auto_20210614_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
