# Generated by Django 3.0.10 on 2021-06-16 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0014_auto_20210615_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='sprites',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprites',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='PokemonApp.Sprites'),
            preserve_default=False,
        ),
    ]
