# Generated by Django 3.0.10 on 2021-06-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0015_auto_20210615_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncaptured',
            name='user',
        ),
    ]
